name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.2'

    - name: Create mock projects
      run: ./tools/shell/mock-projects.sh

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...